version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: gomod
    directory: "/prometheus"
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: gomod
    directory: "/contrib/gin"
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: gomod
    directory: "/contrib/echo"
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: gomod
    directory: "/contrib/fiber"
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: gomod
    directory: "/contrib/fasthttp"
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: gomod
    directory: "/contrib/iris"
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: gomod
    directory: "/contrib/negroni"
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: gomod
    directory: "/contrib/grpc"
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: gomod
    directory: "/examples"
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
